server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://192.168.56.121:18080/auth/realms/universal
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.121:18080/auth/realms/universal
        registration:
          keycloak:
            client-id: kp_app4
            client-secret: 123456789
            provider: keycloak
